import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const siteFont = localfont({
  src: "./../public/fonts/Roboto-Light.ttf",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(siteFont.className)}>{children}</body>
    </html>
  );
}
